export const metadata = {
  title: "{{PROJECT_NAME}}",
  description: "Generated by Polystack",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
