export default function Home() {
  return (
    <main style={{ fontFamily: "system-ui", padding: 32 }}>
      <h1>{{PROJECT_NAME}}</h1>
      <p>Next.js starter generated by Polystack. Database: <code>{{DB}}</code></p>
    </main>
  );
}
