import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

/**
 * Apply optional features on top of a just-scaffolded project.
 * - docker   → writes a language-appropriate Dockerfile + .dockerignore
 * - git      → runs `git init` and makes an initial commit (best-effort)
 * - readme   → ensures a README.md exists
 */
export function applyFeatures({ target, template, features, projectName }) {
  const set = new Set(features || []);
  if (set.has("readme")) ensureReadme(target, projectName, template);
  if (set.has("docker")) writeDocker(target, template);
  if (set.has("git")) gitInit(target, projectName);
}

function ensureReadme(target, name, template) {
  const p = path.join(target, "README.md");
  if (fs.existsSync(p)) return;
  fs.writeFileSync(
    p,
    `# ${name}\n\nGenerated by Polystack (${template}).\n`
  );
}

function writeDocker(target, template) {
  const dockerfile = dockerfileFor(template);
  if (!dockerfile) return;
  fs.writeFileSync(path.join(target, "Dockerfile"), dockerfile);
  fs.writeFileSync(
    path.join(target, ".dockerignore"),
    ["node_modules", "dist", ".next", "target", "vendor", ".venv", "__pycache__", "*.log", ".env"].join("\n") + "\n"
  );
}

function dockerfileFor(template) {
  switch (template) {
    case "java-spring-boot":
      return `# Multi-stage build for Spring Boot
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -B dependency:go-offline
COPY src ./src
RUN mvn -q -B package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
`;
    case "python-fastapi":
      return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
    case "python-django":
      return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
`;
    case "js-express":
      return `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
EXPOSE 3000
CMD ["node", "src/index.js"]
`;
    case "ts-hono":
      return `FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package.json ./
EXPOSE 3000
CMD ["node", "dist/index.js"]
`;
    case "ts-nextjs":
      return `FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 3000
CMD ["npm", "start"]
`;
    case "php-slim":
      return `FROM php:8.3-cli-alpine
WORKDIR /app
COPY . .
RUN apk add --no-cache git unzip \\
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \\
 && composer install --no-dev --optimize-autoloader
EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
`;
    default:
      return null;
  }
}

function gitInit(target, name) {
  try {
    execFileSync("git", ["init", "-q"], { cwd: target, stdio: "ignore" });
    execFileSync("git", ["add", "."], { cwd: target, stdio: "ignore" });
    execFileSync("git", ["commit", "-q", "-m", `chore: initial commit from Polystack (${name})`], {
      cwd: target,
      stdio: "ignore",
      env: {
        ...process.env,
        GIT_AUTHOR_NAME: process.env.GIT_AUTHOR_NAME || "Polystack",
        GIT_AUTHOR_EMAIL: process.env.GIT_AUTHOR_EMAIL || "polystack@local",
        GIT_COMMITTER_NAME: process.env.GIT_COMMITTER_NAME || "Polystack",
        GIT_COMMITTER_EMAIL: process.env.GIT_COMMITTER_EMAIL || "polystack@local",
      },
    });
  } catch {
    // Best-effort; ignore if git is missing or user has no identity configured.
  }
}
